### ISSUE TITLE
Migrate to Qiskit `BackendV2`

### ISSUE THREAD

**Issue by hillmich** [cda-tum/mqt-ddsim#190]
Qiskit has [`BackendV2`](https://qiskit.org/documentation/stubs/qiskit.providers.BackendV2.html) with some improvements on usability. We are currently using [`BackendV1`](https://qiskit.org/documentation/stubs/qiskit.providers.BackendV1.html).

The [Provider page](https://qiskit.org/documentation/apidoc/providers.html#migrating-between-backend-api-versions) summarizes the changes.
> The [BackendV2](https://qiskit.org/documentation/stubs/qiskit.providers.BackendV2.html#qiskit.providers.BackendV2) class re-defined user access for most properties of a backend to make them work with native Qiskit data structures and have flatter access patterns.

If necessary, using [](https://qiskit.org/documentation/stubs/qiskit.providers.BackendV2Converter.html#qiskit.providers.BackendV2Converter) might be a short-term fix, but we should upgrade to the new backend interface.

**Comment by burgholzer** [comment]
Also allows us to drop the "ugly" `QasmQobjExperiment` interface in the QFR and just provide the `QuantumCircuit` interface as the sole means for communication for exchanging circuits.
