### ISSUE TITLE
Hybrid Schrodinger Feynman Simulator reports error for circuits with SWAP gates

### ISSUE THREAD

**Issue by tyi1025** [cda-tum/mqt-ddsim#269]
### mqt.ddsim version

0.1.dev387+g328fdec

### OS

macOS Monterey

### C++ compiler

gcc 13.1.6

### Description

The `HybridSchrodingerFeynmanSimulator` seems to fail when there is a SWAP gate present. It gives `Assertion failed: (targets.size() == 2), function getDD, file Operations.hpp, line 240.` The error disappears as long as you remove the SWAP line.

### Expected behavior

The simulation results should be returned

### How to Reproduce

```auto qc = std::make_unique<qc::QuantumComputation>(2);
    qc->x(0);
    qc->swap(0, 1);
    auto hybridSimulator = std::make_unique<HybridSchrodingerFeynmanSimulator<>>(
        std::move(qc), ApproximationInfo{}, 23);
    auto result = hybridSimulator->simulate(1024U);
```

**Comment by hillmich** [comment]
Thank you for creating the issue! From the top of my head, I would guess that the splitting the circuit between two targets is not supported in the decomposition. I'll have a look.
