### ISSUE TITLE
🐛 Newest version crashes on Docker

### ISSUE THREAD

**Issue by 099NikStone** [cda-tum/mqt-ddsim#288]
### Environment information

mqt-version: 1.19.0
Docker Desktop: 4.22.1

### Description

When running the simulator backend inside a Docker Container, based on circuit transferred from a client outside the Docker container, the error message "Illegal Instruction" pops up, shutting down the Docker Container

### Expected behavior

The simulator is supposed to run a simulate the circuit, returning the simulation results.

### How to Reproduce

After all the setup (Docker Desktop, client and server front- and backends that communicate across the Docker Container), simply hand over a qiskit circuit to the backend, so that it is simulated.

**Comment by burgholzer** [comment]
Hey 👋🏻 

Thanks for raising this issue. Could you provide a little more details on your setup? Specifically,
- Which Docker image are you running?
- How do you install DDSIM in the container?
- Does the error also happen with previous versions of DDSIM?

Just from your description, I can't easily reproduce the error.

**Comment by 099NikStone** [comment]
Hey! 
The image is a custom image, created for a project which includes multiple simulator backends in a single container. 
DDSIM is installed via an editable pip install upon building the image. 
The error doesnt occur with the previous version.  

Sorry for not being able to describe the image more in-depth. If your still unable to recreate the issue, let me know!

**Comment by burgholzer** [comment]
I see. Just some follow up questions. It's rather surprising to me that a local editable install does not work.
- Can you at least share on which kind of container your custom container is built on? are we talking manylinux, ubuntu, something else? 
- Probably most important: which kind of platform are we talking about? x86, arm64, something else?
- Can you share the part of the build/install log related to the editable install? Preferably with the verbose option enabled (so something like `pip install -ve .`)

I might be able to reproduce the error based on the above information.
