### ISSUE TITLE
🐛 BackendV2 unnecessarily transpiles supported gates

### ISSUE THREAD

**Issue by andresbar98** [cda-tum/mqt-ddsim#290]
### Environment information

Python

### Description

Due to a bug, Qiskit transpiles single-qubit gates to `u1`, `u2`, or `u3` gates even though the original gates are in the target gateset. This is being tracked upstream at https://github.com/Qiskit/qiskit/issues/10568.
As a consequence, the new V2 backends in DDSIM actually transpile circuits containing such gates.
In most of the cases, MQT Core and the corresponding parser should be clever enough to reconstruct the original gate, but it is still not ideal.
This issue acts as a tracker for the upstream issue in Qiskit. Once that is resolved, we should more-or-less automatically benefit from it and can enable the respective tests again.

### Expected behavior

Backends should not transpile gates that they declare to support.

### How to Reproduce

Uncomment the respective lines in the `test/python/test_target.py` file and run the tests.

**Comment by burgholzer** [comment]
The upstream issue has been resolved and will be part of `qiskit 0.45.2`.
Once that has dropped, we should be able to close this issue.
