### ISSUE TITLE
✨ Add documentation for Unitary Simulator

### ISSUE THREAD

**Issue by jamesavery** [cda-tum/mqt-ddsim#345]
### What's the problem this feature will solve?

The documentation of the Unitary Simulator is extremely sparse: it's just two sentences that reveal little about how to use it.

I would like to use it in our teaching to inspect linear operator representations of gates and circuits. Could a bit more information - at the very least a couple of examples - be added to the documentation?

Many thanks.

### Describe the solution you'd like

I would like

https://mqt.readthedocs.io/projects/ddsim/en/latest/simulators/UnitarySimulator.html

to contain 

1. Longer term: An overview of the available features and how to use them, 
2. Short term: an example or two showing how to use the Unitary Simulator.

**Comment by burgholzer** [comment]
@jamesavery just updated the documentation on all our simulators. Let me know if you would like any more information in there.
