### ISSUE TITLE
🐛 segfault in M1 mac

### ISSUE THREAD

**Issue by VolodyaCO** [cda-tum/mqt-ddsim#404]
### Environment information

OS: Sonoma 14.5
mqt.ddsim: 1.22.0

### Description

Running a simple circuit. I am trying to access the low level decision diagram using the `CircuitSimulator` and I get a segmentation fault.

Instead, if I simply run the circuit using the DDSIMProvider, I can run the circuit.

### How to Reproduce

```python
from mqt import ddsim
from qiskit import QuantumCircuit

circ = QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.cx(0, 2)

sim = ddsim.CircuitSimulator(circ)

print(sim.get_vector())
```
segfaults in `sim.get_vector()`.

**Comment by VolodyaCO** [comment]
One needs to call `sim.simulate` before getting the vector.

**Comment by burgholzer** [comment]
Thanks for opening this issue. Although you already identified a potential workaround, the underlying error is fixed by #405.
After that, you do not need to call `simulate` before getting the vector. Although, it will just return a `{ 1 }` vector anyway, since nothing has been simulated. At least it fails gracefully.

**Comment by VolodyaCO** [comment]
Thanks @burgholzer Also, is there any python class that represents the graph of the decision diagram?

**Comment by burgholzer** [comment]
> Thanks @burgholzer Also, is there any python class that represents the graph of the decision diagram?

So far, no. The DD package is not exposed to Python in any way. This would be quite a substantial implementation project.

You can make use of https://mqt.readthedocs.io/projects/ddsim/en/latest/api/ddsim.html#mqt.ddsim.pyddsim.CircuitSimulator.export_dd_to_graphviz_file to generate a GraphViz file for visualizing the resulting DD.
This is similar to how our visualization tool MQT DDVis (https://www.cda.cit.tum.de/app/ddvis/) displays the DDs.
