### ISSUE TITLE
Building from clone repository BINDINGS

### ISSUE THREAD

**Issue by jorgevazquezperez** [cda-tum/mqt-ddsim#449]
### Environment information

- OS: NAME=Rocky Linux 8.7 (Green Obsidian)

### Description

In the documentation is said that with the line:

```cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBINDINGS=ON -DBUILD_DDSIM_TESTS=ON```

one can build the package from the clone repository. But, actually, the line that made the job was:

```cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_MQT_DDSIM_BINDINGS=ON -DBUILD_DDSIM_TESTS=ON```

changing `-DBINDINGS=ON` for `-DBUILD_MQT_DDSIM_BINDINGS=ON` in order to get `pybind11` library correctly linked.

### How to Reproduce

1. Clone repository.
2. Install dependencies.
3. Execute the aforementioned CMake command.

**Comment by burgholzer** [comment]
Hey 👋🏼 
The development documentation is definitely out of date here and is definitely due for an update. Thanks for bringing this up. 
The option to explicitly enable tests is also no longer called `BUILD_DDSIM_TESTS` but `BUILD_MQT_DDSIM_TESTS` now.
I'll see whether I can quickly update the documentation over the coming days. 👍🏼
